---
name: Checks

on: [push] # trigger

jobs:
  test-lint: # new job (id)
    name: Test and Lint
    runs-on: ubuntu-20.04 # docker-compose is build in
    steps:
      #steps separated by "-"
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # uses predefined action (you can make your own)
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" #docker compose instead of docker-compose
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
